config/routes.rb
FactCave::Application.routes.draw do

  namespace :admin do

    resources :facts

    root :to => "facts#index"
  end

  get "facts/:slug" => "facts#show", :as => :fact

  get "/healthcheck" => Proc.new {[200, {}, ["OK"]]}

  root :to => Proc.new {[200, {}, ["Fact Cave"]]}

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    alias_action :create, :read, :update, :destroy, :to => :crud
    if user.permissions.include?('edit_fact')
      can :crud, Fact
    end
  end
end

app/models/fact.rb
class Fact
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, :type => String
  field :slug, :type => String
  field :description, :type => String
  field :value, :type => String

  index({:slug => 1}, {:unique => true})

  attr_accessible :description, :name, :value, :slug

  validates_presence_of :name, :value, :slug
  validates :slug, :uniqueness => true, :format => {:with => /\A[a-z0-9-]*\z/}

end

class CurrencyFact < Fact
  field :currency_code, :type => String
  field :value, :type => Float
 
  attr_accessible :currency_code
 
  validate :valid_currency_code
  validates_numericality_of :value

  def self.currency_codes
    currency_data['currency_codes']
  end
 
  def self.currency_symbols
    currency_data['currency_symbols']
  end

  private

  def valid_currency_code
    unless self.class.currency_codes.values.include?(currency_code)
      errors.add(:currency_code, "Currency code is invalid")
    end
  end

  def self.currency_data
    @currency_data ||= YAML.load(File.open("lib/data/iso_4217_currency_codes.yml").read)  
  end
end

class NumericFact < Fact
  field :unit, :type => String
  field :value, :type => Float
  attr_accessible :unit
  validates_numericality_of :value
end

class DateFact < Fact
  field :value, :type => Date
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  field :uid, :type => String
  field :email, :type => String
  field :name, :type => String
  field :permissions, :type => Array
  field :remotely_signed_out, :type => Boolean

  include GDS::SSO::User
  
  attr_accessible :uid, :email, :name, :permissions, as: :oauth

  def to_s
    name
  end
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_filter :authenticate_user!
  before_filter :require_signin_permission! 
end

app/controllers/admin/facts_controller.rb
class Admin::FactsController < Admin::AdminController

  before_filter :initialize_fact, :only => [:new, :create]
  before_filter :find_fact, :only => [:edit, :update, :destroy]
  
  load_and_authorize_resource :except => :index
  
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to admin_facts_path, :alert => exception.message
  end

  after_filter  :log_created_fact, only: [:create]
  around_filter :log_updated_fact, only: [:update]
  after_filter  :log_destroyed_fact, only: [:destroy]

  def index
    @facts = Fact.asc(:slug)
  end

  def new
  end

  def create
    if @fact.save
      redirect_to admin_facts_path, :notice => "#{@fact.name} saved"
    else
      flash[:alert] = "Could not save fact"
      render :new
    end
  end

  def edit
  end

  def update
    if @fact.update_attributes(params[fact_params_key])
      redirect_to admin_facts_path, :notice => "#{@fact.name} updated"
    else
      flash[:alert] = "Could not update fact"
      render :edit
    end
  end

  def destroy
    if @fact.destroy
      redirect_to admin_facts_path, :notice => "#{@fact.name} deleted"
    else
      render :index, :alert => "Could not update fact"
    end
  end

  private

  def find_fact
    @fact = Fact.find params[:id]
  end

  def initialize_fact
    data_type = fact_params_key.to_s
    @fact = data_type.classify.constantize.new params[data_type]
  end

  def fact_params_key
    ['currency_fact', 'date_fact', 'numeric_fact'].each do |type|
      return type if params.has_key?(type) or params[:data_type] == type
    end
    return 'fact'
  end

  def log_created_fact
    if @fact.persisted?
      created_at = Time.now.utc
      msg = {"message" => "#{@fact.class} created at #{created_at}"}
      log_entry = {
        "@fields" => {
          "event_type" => "create",
          "fact_data" => extract_attrs_to_log
        }.merge(msg).merge(user_details),
        "@timestamp" => created_at
      }
      write_log(log_entry)
    end
  end

  def user_details
    { "user" => { "name" => current_user.name, "email" => current_user.email }}
  end

  def log_updated_fact
    before_state = extract_attrs_to_log
    yield
    if @fact.valid?
      updated_at = Time.now.utc
      msg = "#{@fact.class} updated at #{updated_at}"
      log_entry =  {
        "@fields" => {
          "event_type" => "update",
          "fact_data" => {
            "before_state" => before_state,
            "changes" => extract_attrs_to_log.diff(before_state)
          },
          "message" => msg
        }.merge(user_details),
        "@timestamp" => updated_at
      }
      write_log(log_entry)
    end
  end

  def log_destroyed_fact
    if @fact.destroyed?
      deleted_at = Time.now.utc
      before_state = extract_attrs_to_log
      msg = {"message" => "#{@fact.class} destroyed at #{deleted_at}"}
      log_entry = {
        "@fields" => {
          "event_type" => "destroy"
        }.merge("fact_data" => before_state).merge(msg).merge(user_details),
        "@timestamp" => deleted_at
      }
      write_log(log_entry)
    end
  end

  def extract_attrs_to_log
    @fact.attributes.reject { |key, value|
      ["_id", "created_at", "updated_at"].include? key }
  end

  def write_log(entry)
    File.open("#{Rails.root}/log/#{Rails.env}.fact_audit.json.log", "a") {|f|
      f.puts entry.to_json }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include GDS::SSO::ControllerMethods

  protect_from_forgery

  rescue_from Mongoid::Errors::DocumentNotFound, :with => :error_404

  private

  def error_404
    error 404, "not found"
  end

  def error(code, message)
    render :json => {:_response_info => {:status => message}}, :status => code
  end
end

app/controllers/facts_controller.rb
class FactsController < ApplicationController
  def show
    @fact = Fact.find_by(:slug => params[:slug])
    render json: FactPresenter.new(@fact, view_context)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def error_css(resource, field, css_class='error')
    resource.errors[field].present? ? " #{css_class}" : ''
  end

  def error_message_for_field(resource, field)
    if resource.errors[field].present?
      errors = resource.errors[field].join(', ')
      %Q(<span class="help-inline">#{errors}</span>).html_safe
    else
      ''
    end
  end

end

app/helpers/facts_helper.rb
module FactsHelper
  def currency_format_options(selected)
    options = CurrencyFact.currency_codes.to_a
    grouped_options = ['Common', options.select {|o| common_currency?(o)}], ['All', options]
    grouped_options_for_select(grouped_options, selected)
  end
  
  def fact_type(fact)
    if fact.class == Fact
      'Text'
    else
      fact.class.name.gsub('Fact','')
    end
  end

  private

  def common_currency?(currency)
    %w(EUR CNY GBP USD).include?(currency.last)
  end
end

app/views/admin/facts/_form.html.erb
  <fieldset>
    <div class="control-group<%= error_css(@fact, :name) %>"> 
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => "input-xxlarge" %>
        <%= error_message_for_field(@fact, :name) %>
      </div>    
    </div>
    <div class="control-group<%= error_css(@fact, :slug) %>">
      <%= f.label :slug, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :slug, :class => 'input-xxlarge' %>
        <%= error_message_for_field(@fact, :slug) %>
      </div>    
    </div>
    <div class="control-group">
      <%= f.label :description, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :description, :rows => 4, :class => 'input-xxlarge' %>
      </div>    
    </div>
    <div class="control-group<%= error_css(@fact, :value) %>">
      <%= f.label :value, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :value, :class => 'input-xxlarge' %>
        <%= error_message_for_field(@fact, :value) %>
      </div>    
    </div>
    <% if @fact.class == CurrencyFact %>
    <div class="control-group format-options currency">
      <%= f.label :currency_code, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :currency_code, currency_format_options((@fact.currency_code || 'GBP')) %>
      </div>
    </div>
    <% end %>
    <% if @fact.class == NumericFact %>
    <div class="control-group format-options numeric">
      <%= f.label :unit, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :unit, :placeholder => '%' %>
      </div>
    </div>
    <% end %>
    <div class="control-group">
      <div class="controls">
        <%= f.submit :class => 'btn btn-success' %>
      </div>
    </div>
  </fieldset>

app/views/admin/facts/edit.html.erb
<div class="page-header">
  <h1>Editing <%= @fact.name %></h1>
</div>

<%= form_for @fact, :url => admin_fact_path(@fact), :method => 'put',
                    :html => { :class => 'form-horizontal' } do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
<% end %>

app/views/admin/facts/index.html.erb
<h2>Facts</h2>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Slug</th>
      <th>Type</th>
      <th>Value</th>
      <th>Formatted value</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @facts.each do |fact| %>
      <tr>
        <td><%= fact.name %></td>
        <td><%= fact.slug %></td>
        <td><%= fact_type(fact) %></td>
        <td><%= fact.value %></td>
        <td><%= FactPresenter.new(fact, self).formatted_value %>
        <td class="controls">
        <% if can? :crud, fact %>
          <%= link_to "Edit", edit_admin_fact_path(fact.to_param), :class => 'btn btn-primary' %>
          <%= button_to "Delete", admin_fact_path(fact.to_param), 
            :confirm => "Permanently delete '#{fact.name}'?", :method => :delete, :class => 'btn btn-danger' %>
        <% end %>  
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if can? :crud, Fact %>
<%= link_to "New Currency Fact", new_admin_fact_path(:data_type => 'currency_fact'), :class => 'btn btn-success' %>
<%= link_to "New Date Fact", new_admin_fact_path(:data_type => 'date_fact'), :class => 'btn btn-success' %>
<%= link_to "New Numeric Fact", new_admin_fact_path(:data_type => 'numeric_fact'), :class => 'btn btn-success' %>
<%= link_to "New Text Fact", new_admin_fact_path, :class => 'btn btn-success' %>
<% end %>

app/views/admin/facts/new.html.erb
<div class="page-header">
  <h1>New Fact</h1>
</div>

<%= form_for @fact, :url => admin_facts_path(@fact), :html => { :class => 'form-horizontal' } do |f| %>
<%= render :partial => "form", :locals => { :f => f } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fact Cave</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-inverse navbar-fixed-top" role="banner">
    <div class="navbar-inner">
      <div class="container-fluid">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to 'GOV.UK Fact Cave', admin_root_path, :class => "brand" %>
        <nav role="navigation" class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "All Facts", admin_facts_path %></li>
          </ul>
          <ul class="nav pull-right">
            <li class="dropdown">
              <a href="#"
                class="dropdown-toggle"
                data-toggle="dropdown">
                Services
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><a href="http://digital.cabinetoffice.gov.uk/">GDS blog</a></li>
                <li><a href="http://wiki.digital.cabinet-office.gov.uk/">GDS wiki</a></li>
                <li class="divider"></li>
                <li><%= link_to 'Analytics', 'https://www.google.com/analytics/web/#dashboard/default/a26179049w50705554p51337955/'%></li>
                <li class="divider"></li>
                <li><%= link_to 'Sign out', gds_sign_out_path %></li>
              </ul>
            </li>
          </ul>
          <p class="navbar-text pull-right">Signed in as <a href="<%= Plek.current.find('signon') %>"><%= current_user %></a></p>
        </nav><!--/.nav-collapse -->
      </div>
    </div>
  </header>
  <section class="container-fluid" role="main">
    <% [:notice, :alert].select { |k| flash[k].present? }.each do |k| %>
      <div class="alert <%= k %>">
        <%= flash[k] %>
      </div>
    <% end %>

    <%= yield %>

    <hr>

    <footer>
      <p>&copy; GDS. <!-- span class="pull-right">Fact Cave release: TODO </span--></p>
    </footer>

  </section><!--/.container-fluid -->

  <%= javascript_include_tag 'application' %>
</body>
</html>